apiVersion: v2
name: authChart
description: A Helm chart that deploys the Auth application.
type: application
version: "0.0.1"
dependencies:
- name: k3s-authelia
  version: "0.0.1"
  condition: k3s-authelia.enabled
- name: k3s-openldap
  version: "0.0.1"
  condition: k3s-openldap.enabled
